version: "3"

services:
    database:
        env_file: .env
        image: mongo
        container_name: "mongodb"
        ports:
            - "27017-27019"
        volumes:
            - ./mongodb/data:/data/db
    server:
        env_file: .env
        build: ./backend/
        container_name: "express-server"
        ports:
            - "5000:5000"
    client:
        build: ./frontend/
        container_name: "reactjs-client"
        ports:
            - "80:80"
